server.document-root = "/usr/share/webapps/cgit"
server.port           = 80
server.modules       += ( "mod_cgi", "mod_alias", "mod_setenv", "mod_rewrite" )
server.breakagelog    = "/dev/stdout"
server.errorlog       = "/dev/stdout"

mimetype.assign = (
  ".css" => "text/css",
  ".png" => "image/png",
  ".ico" => "image/x-icon"
)

alias.url = (
  "/cgit.css"    => "/usr/share/webapps/cgit/cgit.css",
  "/cgit.png"    => "/usr/share/webapps/cgit/cgit.png",
  "/favicon.ico" => "/usr/share/webapps/cgit/favicon.ico",
  "/robots.txt"  => "/usr/share/webapps/cgit/robots.txt"
)

cgi.assign = ( ".cgi" => "" )

setenv.add-environment = ( "CGIT_CONFIG" => "/etc/cgitrc" )

url.rewrite-once = (
  "^/(cgit\.css|cgit\.png|favicon\.ico|robots\.txt)$" => "$0",
  "^/cgit\.cgi(/.*)?$"                                => "/cgit.cgi$1",
  "^/(.*)$"                                           => "/cgit.cgi/$1"
)
